# Generated by Django 4.2.6 on 2023-12-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_finishedtrips_total_distance_trip_total_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
