# Generated by Django 4.2.6 on 2023-12-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_trip_trip_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedtrips',
            old_name='Trip_created_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='finishedtrips',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='finishedtrips',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
