# Generated by Django 4.2.6 on 2023-12-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
    ]
